### ISSUE TITLE
trac-github can't read a GitHub OAuth secret from a file

### ISSUE THREAD

**Issue by hawkowl** [trac-hacks/trac-github#100]
See https://github.com/trac-hacks/trac-github/blob/master/tracext/github.py#L111 -- it doesn't call read, it tries to strip it :)

**Comment by aaugustin** [comment]
You're obviously the first person trying to use that code! Thanks for the patch.

**Comment by aaugustin** [comment]
Do you need a release on PyPI?

**Comment by hawkowl** [comment]
@aaugustin right now I am using a `git+http://` on the twisted-infra fork with pip for production, but a PyPI release would certainly remove the need for that hack! :)

**Comment by aaugustin** [comment]
I just pushed version 2.1.5 to PyPI with this fix.

**Comment by hawkowl** [comment]
Deployed in prod, all is good. Thanks!

**Comment by rjollos** [comment]
I bumped the version number in https://github.com/trac-hacks/trac-github/commit/23f02223479b876c69d7b6199933d438981ffbe0, but referenced the wrong ticket in the commit message.

**Comment by aaugustin** [comment]
Argh I forgot to push my commit!
