### ISSUE TITLE
Release version 2.3

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-github#119]
I'd like to create a release for version 2.3. It looks like the [change log](https://github.com/trac-hacks/trac-github#master) needs a few updates. I'll go through the commit history, but for anyone that's made changes, if you don't mind adding to the change log that would help.

**Comment by aaugustin** [comment]
I didn't make any changes since 2.2 :-)

All the good work was done by you, @neverpanic, and @raimue.

I'm happy to crank out the release or give permissions to whoever wants them when 2.3 is ready.

**Comment by neverpanic** [comment]
Sure, I'll write a couple of lines.

**Comment by rjollos** [comment]
I added some release steps. @aaugustin, would you mind reviewing? Additionally, we need to add a step for creating a tag and release on GitHub. I looked at the [release page](https://github.com/trac-hacks/trac-github/releases), but I'm unsure whether we need to create and upload the tarball and zip, or if GitHub creates those.

**Comment by aaugustin** [comment]
GitHub creates the release tarball and zip automatically.

**Comment by rjollos** [comment]
Thanks for all the help. Release is published now.

Additional documentation added in https://github.com/trac-hacks/trac-github/commit/d2b067600f3a8a0fb6d270f6151a68a4857cc28a and https://github.com/trac-hacks/trac-github/commit/08e1d3fe4f260e5d1624071eed09a973e4efc566.

**Comment by rjollos** [comment]
Posted an announcement to the [mailing list](https://groups.google.com/d/msg/trac-users/hoE2XkJ9d50/P3aNnRcMEQAJ).

**Comment by aaugustin** [comment]
That was the professional release of trac-github ever :-) 👏
