### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-github#79]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to find trac-hacks plugins, such as yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. More information can be found in the [blog post](http://trac-hacks.org/blog/2015-02-21-trac-hacks-on-github).

Kind regards,
Ryan

(Apologies if I open a ticket against two of your plugins. I'm doing a manual search of GitHub to find Trac plugins and invite plugin authors; it's sometimes difficult to keep everything straight).

**Comment by aaugustin** [comment]
Great initiative!

I tried to transfer the repo but GitHub says "You don't have admin rights to trac-hacks". 

How do we proceed? Do you want me to give you admin access to this repo?

**Comment by rjollos** [comment]
Oh, I forgot a step. Could you try again?

**Comment by aaugustin** [comment]
The transfer worked.

Thanks for this initiative!

**Comment by rjollos** [comment]
Thank you for contributing!
