### ISSUE TITLE
Trac-github suddenly stops working

### ISSUE THREAD

**Issue by mattab** [trac-hacks/trac-github#8]
Hello,

First of all thank you for this great plugin. We've been using it for a few weeks on http://dev.piwik.org and it is great!

However, today we have a problem that the plugin seems disabled, and we can't find a way to enable it again. There has been no change in the files. Do you know, how or why the plugin could stop working and appear disabled, very suddenly ? It was working 24 hours ago: http://dev.piwik.org/trac/ticket/3668#comment:2

We have tried reinstalling via;
$ cd /path/www/dev.piwik.org/trac/plugins
$ pip install -e git://github.com/aaugustin/trac-github.git#egg=TracGitHub-dev

To test I use: 
$ curl --data "test=1" http://dev.piwik.org/trac/github
But that returns the "Error handler not found".

Also our timeline: http://dev.piwik.org/trac/timeline is not showing git commits anymore.

We compared the whole filesystem to backup and nothing changed in the last 24 hours. 

Thank you very much for your help! 

Matt

**Comment by rjollos** [comment]
Occasionally the post-commit hook doesn't work and I see the following in the logs:
```
2016-07-12 13:07:06,356 Trac[github] ERROR: Payload contains unknown commit 55cd9488ccd897bb9b75450852c100d13cf0df02
```

Next time it happens I will try to gather more info, but I think that the changeset isn't being pushed to the remote. Running a fetch on the repository seems to fix the issue.

**Comment by aaugustin** [comment]
Yes, we've seen that on Django as well. It appears to be a race condition where Trac is notified but the git fetch doesn't get the commit. I never figured out when it happens exactly.

**Comment by rjollos** [comment]
I wonder if we could reorder the code and implement a retry of `git remote update --prune` when an unknown commit is encountered. Have you given any thought to possible fixes/workarounds?

**Comment by aaugustin** [comment]
I remember trying various things, but that was several years ago, so unfortunately I don't remember the details.
