### ISSUE TITLE
Package on PyPI has higher version number than repository code

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-github#85]
The package on PyPI is listed as 2.1.2. The master branch shows 2.1.1 in `setup.py`.

**Comment by rjollos** [comment]
Only in trac-github-2.1.1: .git
    Only in trac-github-2.1.1: .gitignore
    Only in trac-github-2.1.1: LICENSE
    Only in trac-github-2.1.2: PKG-INFO
    Only in trac-github-2.1.1: README.md
    Only in trac-github-2.1.1: runtests.py
    diff -u trac-github-2.1.1/setup.cfg trac-github-2.1.2/setup.cfg
    --- trac-github-2.1.1/setup.cfg	2015-08-04 14:26:36.000000000 -0700
    +++ trac-github-2.1.2/setup.cfg	2015-03-14 02:59:04.000000000 -0700
    @@ -1,2 +1,8 @@
     [wheel]
     universal = 1
    +
    +[egg_info]
    +tag_build = 
    +tag_date = 0
    +tag_svn_revision = 0
    +
    diff -u trac-github-2.1.1/setup.py trac-github-2.1.2/setup.py
    --- trac-github-2.1.1/setup.py	2015-08-04 14:26:36.000000000 -0700
    +++ trac-github-2.1.2/setup.py	2015-03-14 02:57:25.000000000 -0700
    @@ -2,7 +2,7 @@
 
     setup(
         name='trac-github',
    -    version='2.1.1',
    +    version='2.1.2',
         author='Aymeric Augustin',
         author_email='aymeric.augustin@m4x.org',
         url='https://github.com/aaugustin/trac-github',
    Only in trac-github-2.1.2: trac_github.egg-info
    Common subdirectories: trac-github-2.1.1/tracext and trac-github-2.1.2/tracext

**Comment by aaugustin** [comment]
Fixed in 141093deb4492af5235238ce85781b89ead56144. Thanks!
