### ISSUE TITLE
Warning: Scope has changed from "" to "".

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-github#86]
I've been seeing the following error when attempting to authenticate through GitHub.

    2015-08-04 21:38:45,841 Trac[main] ERROR: Internal Server Error: 
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/trac/web/main.py", line 550, in _dispatch_request
        dispatcher.dispatch(req)
      File "/usr/local/lib/python2.7/dist-packages/trac/web/main.py", line 243, in dispatch
        resp = chosen_handler.process_request(req)
      File "build/bdist.linux-x86_64/egg/tracext/github.py", line 45, in process_request
        self._do_oauth(req)
      File "build/bdist.linux-x86_64/egg/tracext/github.py", line 66, in _do_oauth
        client_secret=client_secret)
      File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 203, in fetch_token
        self._client.parse_request_body_response(r.text, scope=self.scope)
      File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
        self.token = parse_token_response(body, scope=scope)
      File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
        validate_token_parameters(params)
      File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 406, in validate_token_parameters
        raise w
    Warning: Scope has changed from "" to "".

The following patch seems to have fixed the issue:

```diff
diff --git a/tracext/github.py b/tracext/github.py
index 6b2bcfd..835d68c 100644
--- a/tracext/github.py
+++ b/tracext/github.py
@@ -79,7 +79,7 @@ class GitHubLoginModule(LoginModule):
         redirect_uri = req.abs_href.github('oauth')
         # Inner import to avoid a hard dependency on requests-oauthlib.
         from requests_oauthlib import OAuth2Session
-        return OAuth2Session(client_id, redirect_uri=redirect_uri, scope=[])
+        return OAuth2Session(client_id, redirect_uri=redirect_uri, scope=['user:email'])
 
     def _client_config(self, key):
         assert key in ('id', 'secret')
```

I'm interested to hear what you think about the change. Thanks.

**Comment by aaugustin** [comment]
The current code doesn't request the user:email scope for privacy reasons.

Originially I wrote this plugin for Django's Trac instance which doesn't need your private GitHub email. It will use your public GitHub email if you have one.

**Comment by rjollos** [comment]
Any idea why the original error was seen?

**Comment by aaugustin** [comment]
Not really :-/ Perhaps a different version of oauthlib?

**Comment by rjollos** [comment]
I'm using `requests-oauthlib` 0.5. What version are you running?

**Comment by aaugustin** [comment]
The problem is at the level of oauthlib (trac-github wraps requests-oauthlib which wraps oauthlib). I can't tell you right now which version of oauthlib we're using because I don't have access to this server anymore and the configuration files don't pin a version :-(

Can you try `scope=['']`? Looking at the implementation (https://github.com/idan/oauthlib/blob/16cd3b255b2c86ec7da412357cad899c72d8dbf7/oauthlib/oauth2/rfc6749/tokens.py#L28-L44), I suspect the weird error message stems from comparing `{}` to `{''}` and then displaying `''.join({}) != ''.join({''})` (not the clearest explanation but I hope you get the idea).

If this works, we have two courses of action:

1. if we convince ourselves that `scope=['']` is the proper way not to require any scopes, make this change — and hopefully not break older version of oauthlib, but at worst, we can tell users to upgrade
2. otherwise, report the bug to the maintainers of `oauthlib`

**Comment by rjollos** [comment]
Your suggested change seems to work well. Nice code reading ;)

I'm deploying the plugin for the jQuery site and we aren't ready to go live for at least another week. I can report back here after we've had a chance to do more testing if you'd like to wait a short while longer before pushing the change.

**Comment by aaugustin** [comment]
Sure, please let me know your findings.

I'll try to grab the person who administrates code.djangoproject.com, update dependencies and check if this change is needed for us as well.

**Comment by rjollos** [comment]
> I'll try to grab the person who administrates code.djangoproject.com, update dependencies and check if this change is needed for us as well.

There's a Django team member that has been working with the Trac team on a [Python 3 port](https://groups.google.com/d/msg/trac-dev/Rxqr-4Y0fTU/iCrNqOFj1DgJ). We could ask him if you think that would be useful.

**Comment by aaugustin** [comment]
I just reproduced the bug and confirmed the fix.

I released version 2.1.3 on PyPI. Enjoy!

**Comment by aaugustin** [comment]
By the way, let me know when you deploy the plugin on bugs.jquery.com: since it's a high profile project, I'll mention it in the README ;-)

**Comment by rjollos** [comment]
Will do. It should be deployed soon thanks to your help!

Do you think `requests-oauthlib >= 0.5` should be enforced in `setup.py`?:

```python
install_requires = ['requests-oauthlib >= 0.5']
```

**Comment by rjollos** [comment]
Also considering to deploy this on trac-hacks.org :)

**Comment by aaugustin** [comment]
`requests-oauthlib` isn't a requirement; it's only needed if you want to use GitHub login. I'd rather not make it a requirement.

**Comment by rjollos** [comment]
In that case we can specify `extras_require`. I'll take a look at the code to make sure this makes sense with your design.

**Comment by aaugustin** [comment]
Why not — I'm not very good with setup.py (all the more since best practices keep changing quickly and there's no decent documentation about which option does what).

**Comment by rjollos** [comment]
If `requests-oauthlib` is not installed, the Component appears on the plugin admin panel and can be enabled. It loads during environment startup. The following is found in the logs when visiting `/github/oauth`:

```
02:04:23 AM Trac[main] ERROR: Internal Server Error: 
Traceback (most recent call last):
  File "/home/user/Workspace/trac-github-dev/pve/local/lib/python2.7/site-packages/trac/web/main.py", line 554, in _dispatch_request
    dispatcher.dispatch(req)
  File "/home/user/Workspace/trac-github-dev/pve/local/lib/python2.7/site-packages/trac/web/main.py", line 247, in dispatch
    resp = chosen_handler.process_request(req)
  File "/home/user/Workspace/trac-github-dev/trac-github/tracext/github.py", line 56, in process_request
    self._do_oauth(req)
  File "/home/user/Workspace/trac-github-dev/trac-github/tracext/github.py", line 71, in _do_oauth
    oauth = self._oauth_session(req)
  File "/home/user/Workspace/trac-github-dev/trac-github/tracext/github.py", line 92, in _oauth_session
    from requests_oauthlib import OAuth2Session
ImportError: No module named requests_oauthlib
```

After the change the following is seen in the debug-level logs on environment startup:
```
02:22:27 AM Trac[loader] DEBUG: Skipping "github.auth = tracext.github:GitHubLoginModule [oauth]": ("DistributionNotFound: requests-oauthlib>=0.5" not found)
02:22:27 AM Trac[loader] DEBUG: Loading github.browser from /home/user/Workspace/trac-github-dev/pve/lib/python2.7/site-packages/trac_github-2.1.3-py2.7.egg
02:22:27 AM Trac[loader] DEBUG: Loading github.postcommithook from /home/user/Workspace/trac-github-dev/pve/lib/python2.7/site-packages/trac_github-2.1.3-py2.7.egg
```

`GitHubLoginModule` is still shown on the plugin admin panel, but that seems to be an issue with the Trac Component architecture. The same error results when visiting `/github/oauth`. Some improvements may need to be made to the Trac architecture.

For now, the main advantage to the proposed change is the debug level log message, would could help track down user installation issues more quickly. It's not a huge advantage, but I don't see any downsides. See pull request #89.

**Comment by rjollos** [comment]
I had meant to create the branch in my fork. Sorry about that!

**Comment by rjollos** [comment]
Raised a ticket for some of the points mentioned above: [#12158](http://trac.edgewall.org/ticket/12158).

**Comment by rjollos** [comment]
> By the way, let me know when you deploy the plugin on bugs.jquery.com: since it's a high profile project, I'll mention it in the README ;-)

bugs.jquery.com and bugs.jqueryui.com were updated yesterday and are now running the trac-github plugin.
