### ISSUE TITLE
Hide emails from Trac tickets 

### ISSUE THREAD

**Issue by Razzeee** [trac-hacks/trac-github#92]
Hi, 

would it be possible to hide the email address from the ticket updates or replace it with a generic? 
Even better would be matching them to our Trac users, but we're not using github auth. 

Could not find anything documented.

**Comment by aaugustin** [comment]
Are you talking about removing email addresses found in git commits from notification emails sent by Trac?

**Comment by Razzeee** [comment]
No from the Trac ticket. See for an example: http://trac.kodi.tv/ticket/15727#comment:11

One of our team members this about that:
"Beware, this will print your git name/email on trac, and set the owner to that name, not your trac account. Why I just avoid it."

**Comment by aaugustin** [comment]
This doesn't have anything to do with trac-github. It's handled by the [commit ticket updater](http://trac.edgewall.org/wiki/CommitTicketUpdater).

trac-github merely tells Trac to fetch changes from the GitHub repository. This triggers a notification which may trigger changes on the ticket but that's entirely dependent on your configuration and outside of trac-github's control.

Besides I'm not seeing email addresses, only the local part.

**Comment by Razzeee** [comment]
Sorry, still learning how trac does things! Thank you!

**Comment by rjollos** [comment]
Mapping changeset username is discussed in [#10640](http://trac.edgewall.org/ticket/10640).
