### ISSUE TITLE
PostCommitHook not working

### ISSUE THREAD

**Issue by Razzeee** [trac-hacks/trac-github#93]
Hey everybody,

I think github has changed their PostCommitHooks (no clue when) does this still work? And if it does, how does it need to be configured, as the readme is talking about settings we don't get offered.
https://github.com/trac-hacks/trac-github#post-commit-hook

Thx

**Comment by aaugustin** [comment]
Indeed the GitHub UI changed a little bit, see the change I just committed. Hooks still work.
