### ISSUE TITLE
Better visibility of behavior for users that don't have a public email

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-github#94]
The plugin will only use a user's name and email from GitHub if they are public, as [previously described](https://github.com/trac-hacks/trac-github/issues/86#issuecomment-127889173). In the case that `[notification] always_notify_updater` is true, users with a public email in their GitHub profile will receive notifications, whereas users without a public email in their GitHub profile will not unless they have explicitly set their email address in their Preferences. For the jQuery Trac sites we'd like to make the behavior more consistent, or at least more explicit. Therefore, I've considered the following and would like to get some feedback on whether you think one or both is a good idea:

* Add a notice on login for a user that doesn't have a public email address in their GitHub profile. The notice would be something like: *You will not receive email notifications unless you set your email address in preferences [x]* (with preferences being a link to `/prefs` and [x] being a dismiss button). The notice could persist on every page until the name and email are set, or until the notice is explicitly dismissed (AccountManagerPlugin has similar behavior for verification of emailed registration tokens).
* Allow users with a private name and email in their GitHub profile to explicitly opt-in to having their name and email set in Trac preference data (is it even possible?).

**Comment by aaugustin** [comment]
You can ask for the `user:email` scope to get access to the private email.

However I'm not sure GitHub's UI lets you decline that scope and still proceed with the login.

What about making that a configuration option of the plugin?

**Comment by rjollos** [comment]
> What about making that a configuration option of the plugin?

Yeah, I think a configuration option is a good idea.

I'll investigate this coming weekend and propose one or more pull-requests.

**Comment by neverpanic** [comment]
The configuration options to request the `user:email` scope is now merged with #105. Do you want to keep this open to track implementing the notification behavior you outlined above?

**Comment by rjollos** [comment]
> However I'm not sure GitHub's UI lets you decline that scope and still proceed with the login.

It looks like GitHub does not let you decline the scope and proceed with the login. I tested 2.3dev after making my email address private and with `[github] request_email` set to `True`:

![screen shot 2016-10-17 at 17 02 44](https://cloud.githubusercontent.com/assets/1152089/19460036/c1237146-948c-11e6-8eeb-4a99e59b4f69.png)

> Do you want to keep this open to track implementing the notification behavior you outlined above?

As for the other idea, of adding a notice, it might be more appropriate to add the behavior to Trac. I'll discuss with the team that requested the behavior and reply back here.

**Comment by rjollos** [comment]
See also [Trac #12165](https://trac.edgewall.org/ticket/12165). Sounds like `[github] request_email` will be good enough for the jQuery UI site. Thanks for implementing!
