### ISSUE TITLE
Should documentation mention that a repository resync is needed?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-github#96]
In the post-commit-hook section of the documentation, it looks like there needs to be an initial sync of the cache:

```sh
trac-admin $env repository resync "<project>"
```
or
```sh
trac-admin $env repository resync "(default)"
```

Does that seem correct?

Also, author names that Trac caches look like `Full Name <email@domain.com>`. In order for the CommitTicketUpdater to function, I suspect that reverse mapping from email address to Trac user id needs to be enabled. It is disabled by default.

```ini
[git] trac_user_rlookup = enabled
```

I will edit the documentation if you agree with the changes.

**Comment by aaugustin** [comment]
Sure, go ahead. You seem to know this stuff better than I do ;-) Thanks!

**Comment by rjollos** [comment]
Thanks, I'm actually not 100% sure that I'm correct on those points, but I'll do some additional testing to confirm.

**Comment by aaugustin** [comment]
Changes look good. (I don't know enough about Trac to confirm they're correct.) Thanks!
