### ISSUE TITLE
Document steps for local development against the GitHub OAuth API

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-github#99]
Mentioned in #97, I'll document the steps for testing the plugin in a local development environment against the GitHub OAuth API. I used [ngrok](https://developer.github.com/webhooks/configuring/).

Related: steps for setting up a webhook were adapted to the new GitHub page layout in 14f0ae06afe81b98c4c4bc25cb2d7608aa0a477a.

**Comment by rjollos** [comment]
The README.md is getting a bit lengthy. Would it make sense to move the [development section](https://github.com/trac-hacks/trac-github#development) when adding this additional content?

**Comment by neverpanic** [comment]
Development and Release Steps are the only two sections that could be moved to a separate development document, but the largest part of the README seems to be actual documentation, so I'm not sure that's very useful.

We could split the documentation into multiple files, but that's probably a lot of effort for little gain.

**Comment by aaugustin** [comment]
It's convenient to have everything in the README. Perhaps we could add a table of contents to make it easier to navigate.

**Comment by rjollos** [comment]
[Configuring Your Server](https://developer.github.com/webhooks/configuring/) was a good resource in getting this working the first time.
